# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml

name: robot_automation

trigger:
- master

stages:
- stage: CI_Checks
  jobs:
  - job: 'Test'
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 1

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary chromedriver-autoinstaller
      displayName: 'Install dependencies'

    - powershell: robot -d Results -v url:https://opensource-demo.orangehrmlive.com -v userName:Admin -v password:admin123  .\Test\Login.robot
      displayName: 'Run Robot Scripts'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: outputxunit.xml
        searchFolder: 'D:\a\1\s\'
        condition: succeededOrFailed()
        displayName: 'Publish Test Results outputxunit.xml'